# Generated by Django 5.1.2 on 2024-10-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer_1', models.TextField(blank=True, null=True)),
                ('answer_2', models.TextField(blank=True, null=True)),
                ('answer_3', models.TextField(blank=True, null=True)),
                ('answer_4', models.TextField(blank=True, null=True)),
                ('answer_5', models.TextField(blank=True, null=True)),
                ('answer_6', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(max_length=10)),
                ('comment', models.TextField()),
            ],
        ),
    ]
